services:
  pci-ltd:
    build:
      context: .
      dockerfile: Dockerfile
    image: pci-ltd:latest
    container_name: pci-ltd
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - pci-stats:/data

volumes:
  pci-stats:
    driver: local
