import type { VisitorSession } from "./types";

export const seedSessions: VisitorSession[] = [
  {
    id: "S-GB-3324",
    country: "United Kingdom",
    city: "London",
    region: "Europe",
    source: "Bing",
    browser: "Edge 134",
    device: "Desktop",
    duration: "06m 41s",
    timestamp: "2026-05-04T08:11:00Z",
    pages: 3,
    coordinates: [-0.1, 51.5],
    journey: [
      {
        path: "/",
        label: "Home",
        at: "08:11",
        thumbnail: "",
      },
      {
        path: "/services",
        label: "Services",
        at: "08:13",
        thumbnail: "",
      },
      {
        path: "/contact",
        label: "Contact",
        at: "08:16",
        thumbnail: "",
      },
    ],
  },
  {
    id: "S-US-9930",
    country: "United States",
    city: "New York",
    region: "North America",
    source: "Direct",
    browser: "Safari 18",
    device: "Mobile",
    duration: "14m 01s",
    timestamp: "2026-05-04T14:17:00Z",
    pages: 3,
    coordinates: [-74.0, 40.7],
    journey: [
      {
        path: "/",
        label: "Home",
        at: "14:17",
        thumbnail: "",
      },
      {
        path: "/about",
        label: "About",
        at: "14:20",
        thumbnail: "",
      },
      {
        path: "/contact",
        label: "Contact",
        at: "14:28",
        thumbnail: "",
      },
    ],
  },
  {
    id: "S-IN-7742",
    country: "India",
    city: "Bengaluru",
    region: "Asia",
    source: "LinkedIn",
    browser: "Chrome 135",
    device: "Desktop",
    duration: "11m 26s",
    timestamp: "2026-05-03T19:32:00Z",
    pages: 3,
    coordinates: [77.6, 12.9],
    journey: [
      {
        path: "/",
        label: "Home",
        at: "19:32",
        thumbnail: "",
      },
      {
        path: "/services",
        label: "Services",
        at: "19:35",
        thumbnail: "",
      },
      {
        path: "/speakez",
        label: "SpeakEZ",
        at: "19:42",
        thumbnail: "",
      },
    ],
  },
  {
    id: "S-AU-1901",
    country: "Australia",
    city: "Sydney",
    region: "Oceania",
    source: "Google Search",
    browser: "Firefox 137",
    device: "Desktop",
    duration: "04m 42s",
    timestamp: "2026-05-03T22:07:00Z",
    pages: 2,
    coordinates: [151.2, -33.9],
    journey: [
      {
        path: "/",
        label: "Home",
        at: "22:07",
        thumbnail: "",
      },
      {
        path: "/online-safety",
        label: "Online Safety",
        at: "22:11",
        thumbnail: "",
      },
    ],
  },
];
